/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DialogosRouteImport } from './routes/dialogos'
import { Route as PraticaDialogueIdRouteImport } from './routes/pratica.$dialogueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogosRoute = DialogosRouteImport.update({
  id: '/dialogos',
  path: '/dialogos',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticaDialogueIdRoute = PraticaDialogueIdRouteImport.update({
  id: '/pratica/$dialogueId',
  path: '/pratica/$dialogueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dialogos': typeof DialogosRoute
  '/pratica/$dialogueId': typeof PraticaDialogueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dialogos': typeof DialogosRoute
  '/pratica/$dialogueId': typeof PraticaDialogueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dialogos': typeof DialogosRoute
  '/pratica/$dialogueId': typeof PraticaDialogueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dialogos' | '/pratica/$dialogueId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dialogos' | '/pratica/$dialogueId'
  id: '__root__' | '/' | '/dialogos' | '/pratica/$dialogueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DialogosRoute: typeof DialogosRoute
  PraticaDialogueIdRoute: typeof PraticaDialogueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogos': {
      id: '/dialogos'
      path: '/dialogos'
      fullPath: '/dialogos'
      preLoaderRoute: typeof DialogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratica/$dialogueId': {
      id: '/pratica/$dialogueId'
      path: '/pratica/$dialogueId'
      fullPath: '/pratica/$dialogueId'
      preLoaderRoute: typeof PraticaDialogueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DialogosRoute: DialogosRoute,
  PraticaDialogueIdRoute: PraticaDialogueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
